### ISSUE TITLE
Can we push multiple Sheets at same time?

### ISSUE THREAD

**Issue by howardpen9** [bcrant/Tableau2Slack#1]
Let's said we have multiple dashboard want to push,  can we do that? Or I just need to deploy other python code

**Comment by bcrant** [comment]
@howardpen9 Hello! There's a few ways you could do that. 

This will be easier to exemplify when I'm back at a computer -- out of town for the weekend. 

If you want to have the Slack bot post multiple dashboards at the same time...
Edit the JSON payload in the Python script. You will need to duplicate the Slack Block Kit section that posts the image and give it new variables. One new block per view/dashboard.

If you want many dashboards to post at different intervals, you can just schedule the script multiple times using different environment variables. 

Hope that makes sense. Let me know how I can help! Will be back next week. Depending on how you have this deployed you could suite either case.

**Comment by howardpen9** [comment]
ok, I will try and upload a my version on new branch.


If you want to have the Slack bot post multiple dashboards at the same time...
Edit the JSON payload in the Python script. You will need to duplicate the Slack Block Kit section that posts the image and give it new variables. One new block per view/dashboard.

**Comment by bcrant** [comment]
No updates, so going to close this now.
